include: linux: qcom_scm.h: Expect something in `return`
*Fixes:-
../include/linux/qcom_scm.h:249:32: error: non-void function does not return a value [-Werror,-Wreturn-type]

Signed-off-by: kartik-commits <kartiklashkare@gmail.com>